archive:
  one: 'Archive'
  other: 'Archives'

category:
  one: 'Category'
  other: 'Categories'
tag:
  one: 'Tag'
  other: 'Tags'
post:
  one: 'Post'
  other: 'Posts'
page:
  one: 'Page'
  other: 'Pages'
prev: 'Previous'
next: 'Next'

all: 'All'
home: 'Home'
title: 'Title'
about: 'About'
recent: 'Recent'
friends: 'Friends'
read_more: 'Read more'
user_name: 'User name'
click_back_to_the_top: 'Click back to the top'

search_input_placeholder: 'Search everything..'

